spring.application.name=26-RestApi-Project-Employe-03

# server Port
server.port=9011

# conect Mysql Database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/restapi
spring.datasource.username=root
spring.datasource.password=root

# Conect With Data JPa / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# viewrosesolver propeties
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp